name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_NETWORK_POOL}"

volumes:
  habitat-config:
  redis-data:
  redis-config:

secrets:
  REDIS_PASSWORD:
    file: ${SECRETS_DIR}/REDIS_PASSWORD


services:

  habitat-config-cache:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-cache
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "cache"
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro
      - redis-config:/habitat-config/target/redis

  redis:
    build:
      context: ./redis
    container_name: ${APP_NAME_HOST}_redis
    restart: unless-stopped
    expose:
      - '6379'
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/redis.env
        required: false
    environment:
      REDIS_PASSWORD_FILE: "/run/secrets/REDIS_PASSWORD"
    secrets:
      - REDIS_PASSWORD
    volumes:
      - redis-data:/data
      - redis-config:/config
    networks:
      internal:
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$$(cat $${REDIS_PASSWORD_FILE})\" ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      habitat-config-cache:
        condition: service_completed_successfully
